apiVersion: v1
kind: Service
metadata:
  name: ldap-server
spec:
  selector:
    app: ldap-server
  ports:
  - name: ldap
    port: 389
    targetPort: 389
  - name: smb
    port: 445
    targetPort: 445
